name: Trigger Local Terraform

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      username:
        description: 'abcd'
        required: true
        default: 'admin'
        type: string
env:
  TF_JIRA_USERNAME: "${{ github.event.inputs.username }}"

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print input values
        run: |
          echo "Environment: ${{ github.event.inputs.username }}"
          echo "Message: ${{ github.event.inputs.username }}"

  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit message
        run: echo "TF_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Terraform Apply
        env:
            TF_VAR_commit_message: ${{ env.TF_COMMIT_MESSAGE }}
        run: terraform apply -auto-approve
        
      - name: Print the input message
        run: |
          echo "Username: ${{ github.event.inputs.username }}"

      - name: Use password safely (not printed)
        env:
          PASSWORD: ${{ secrets.USER_TOKEN }}
        run: |
          echo "Using password internally, not printing it."
          # Example internal use:
          curl -u "${{ github.event.inputs.username }}:$PASSWORD" https://example.com/api

  terraform-local:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          clean: false
          persist-credentials: false
      
      # - name: Sleep 10 seconds
      #   run: Start-Sleep -Seconds 10
      #   shell: pwsh

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        # run: terraform apply -auto-approve
        # env:
        #   TF_VAR_username: ${{ github.event.inputs.username }}
