name: Trigger Local Terraform

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:
    # inputs:
    inputs:
      issue_key:
        description: "Enter the Jira issue key (e.g. MSD-123)"
        required: true
      username:
        description: 'abcd'
        required: true
        default: 'admin'
        type: string
      
env:
  TF_JIRA_USERNAME: "${{ github.event.inputs.username }}"
  TF_JIRA_TOKEN: "YXJ5LnN1d2FuZGlAaXplbm8uY29tOkFUQVRUM3hGZkdGMDY2YUpTVW4tcVk1OFJJLWhZSUVuejk2a2I1X1pueXhpbmc2QXFDOG5qOUFaV1RQY0ZZUTJYOXBPdE93U0sxWktRVXlaTGFZdHFGTDVFSFNqZVZTdndmcWtTRjZxak5YS3cxVXhyN25Say03Qzl5MWJUVW5WYjF0VHdPUzlBb2M2akJ3ZzBZb18tS3Vfa3ZSZFJBY21uTnBRRUljOEI2YTRhaWxxaUJuT19BVT0yRThCQjY3OA=="

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print input values
        run: |
          echo "Environment: ${{ github.event.inputs.username }}"
          echo "Message: ${{ github.event.inputs.username }}"

  terraform-local:
    runs-on: self-hosted

    steps:
      - name: Check whoami
        run: whoami

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          clean: false
          persist-credentials: false
      
      # - name: Sleep 10 seconds
      #   run: Start-Sleep -Seconds 10
      #   shell: pwsh

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
          -var="username=${{ github.event.inputs.username }}" \
          -var="jira_token=${{ env.TF_JIRA_TOKEN }}"
        # run: terraform apply -auto-approve
        # env:
        #   TF_VAR_username: ${{ github.event.inputs.username }}
