name: Trigger Local Terraform

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'
        required: true
        default: 'admin'
        type: string

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit message
        run: echo "TF_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Terraform Apply
        env:
            TF_VAR_commit_message: ${{ env.TF_COMMIT_MESSAGE }}
        run: terraform apply -auto-approve
        
      - name: Print the input message
        run: |
          echo "Username: ${{ github.event.inputs.username }}"

      - name: Use password safely (not printed)
        env:
          PASSWORD: ${{ secrets.USER_TOKEN }}
        run: |
          echo "Using password internally, not printing it."
          # Example internal use:
          curl -u "${{ github.event.inputs.username }}:$PASSWORD" https://example.com/api

  terraform-local:
    runs-on: self-hosted

    env:
      # TF_CLOUD_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VAR_jira_token: ${{ secrets.JIRA_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
