name: Trigger Local Terraform

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'
        required: true
        default: 'admin'
        type: string

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input message
        run: |
          echo "Username: ${{ github.event.inputs.username }}"


  terraform-local:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Run Terraform Plan
        run: |
          cd terraform
          terraform plan

      # Optional: apply
      - name: Run Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd terraform
          terraform apply -auto-approve
